export enum TaskState { waiting, starting, in_progress, unpacking, verifying, finished, failed }

export struct TaskData {
	id: int,
	name: string,
	details: string,
	progress: float,
	state: TaskState,
}

export struct TasksGroup {
	name: string,
	tasks: [TaskData],
}

export struct Content {
	img: image,
	link: string,
	text: string
}

export struct Mod {
	name: string,
	description: string,
	version: string,
	enabled: bool,
	default: bool,
	author: string,
	url: string,
	image: image,
	loading: bool
}
