export component ButtonRegular inherits Rectangle {
	callback on_click;

	in-out property <bool> primary: false;

	background: area.has-hover ? (primary ? #007965 : #989898) : (primary ? #006857 : #848484);
	border-width: 1px;
	border-radius: 1000px;
	border-color: primary ? #25B39C : #707070;

	area := TouchArea {
		clicked => { on_click(); }
	}

	states [
	    press when area.pressed : {
			opacity: 0.4;
			in {
				animate opacity { duration: 80ms; easing: ease-in-out; }
			}
			out {
				animate opacity { duration: 240ms; easing: ease-in-out; }
			}
		}
	]
	animate background { duration: 250ms; easing: ease-in-out; }

	opacity: 1.0;

	@children
}
