export component ButtonGrowable {
	width: 32px;
	height: 32px;

	callback on_click;

    Rectangle {
		background: rgba(0, 0, 0, 0);
		border-width: 0px;
		clip: false;

		area := TouchArea {
			mouse-cursor: pointer;
			clicked => { on_click(); }
		}
		
		states [
		    press when area.pressed : {
				width: 30px;
				height: 30px;
				opacity: 0.6;
				in {
					animate width, height, opacity { duration: 60ms; easing: ease-in-out; }
				}
				out {
					animate width, height, opacity { duration: 250ms; easing: ease-in-out; }
				}
			}
			hover when area.has-hover : {
				width: 36px;
				height: 36px;
				in-out {
					animate width, height { duration: 250ms; easing: ease-in-out; }
				}
			}
		]

		width: 32px;
		height: 32px;
		opacity: 1.0;

		@children
	}
}
