export component CleanSpinner inherits Rectangle {
	in property <length> size: 24px;
	in-out property <bool> spinning: true;

	height: self.size;
	width: self.size;
	border-radius: 100000px;
	border-width: 1px;
	border-color: rgba(255, 255, 255, 0.4);
	drop-shadow-blur: 2px;

	Rectangle {
		width: root.width - 1px;
		height: root.height - 1px;
		border-radius: 1000000px;
		border-width: 1px;
		border-color: rgba(255, 255, 255, 0.1);
	}
}
