import { ButtonRegular } from "button_regular.slint";
import { DialogData, DialogType, DialogSeverity } from "typedef/dialog_utils.slint";

export component FallbackDialog inherits Window {
	in property <string> name;
	title: name;
	width: 600px;
	min-height: 180px;
	always-on-top: true;
	default-font-size: 20px;

	in-out property<DialogData> dialog-data: { shown: false, type: DialogType.basic, severity: DialogSeverity.info, content: "" };

	callback close();
	callback confirm();

	Rectangle {
	   VerticalLayout {
			spacing: 20px;
			alignment: space-around;
			HorizontalLayout {
				alignment: start;
				Image {
					width: 50px;
					height: 50px;
					colorize: white;
					source: root.dialog-data.severity == DialogSeverity.info ? @image-url("assets/icons/info.svg") : @image-url("assets/icons/error.svg");
				}
				Text { text: dialog-data.content; }
			}
			HorizontalLayout {
				alignment: end;
				if dialog-data.type == DialogType.confirmation : ButtonRegular {
					primary: false;
					on_click => { close() }
					Text { text: "Cancel"; }
				}
				ButtonRegular {
					primary: true;
					on_click => {
						close();

						if (root.dialog-data.type == DialogType.confirmation) {
							confirm();
						}
					}
					Text { text: root.dialog-data.type == DialogType.confirmation ? "Proceed" : "Ok"; }
				}
			}
		}
	}
}
