import { ButtonRegular } from "button_regular.slint";
import { DialogType } from "typedef/dialog_utils.slint";

export component FallbackDialog inherits Window {
	in property <string> name;
	title: name;
	min-width: 400px;
	min-height: 180px;
	always-on-top: true;

	callback close();
	callback confirm();
	in-out property <string> text;
	in-out property <DialogType> type;

	Rectangle {
	   VerticalLayout {
			spacing: 20px;
			alignment: space-around;
			HorizontalLayout {
				alignment: start;
				Image {
					width: 50px;
					height: 50px;
					source: type == DialogType.basic ? @image-url("assets/icons/error.svg") : @image-url("assets/icons/info.svg");
				}
				Text {
					text: root.text;
				}
			}
			HorizontalLayout {
				alignment: end;
				ButtonRegular {
					visible: type == DialogType.confirmation;
					primary: false;
					on_click => { close() }
					Text { text: "Cancel"; }
				}
				ButtonRegular {
					primary: true;
					on_click => {
						close();

						if (type == DialogType.confirmation) {
							confirm();
						}
					}
					Text { text: type == DialogType.confirmation ? "Proceed" : "Ok"; }
				}
			}
		}
	}
}
