import { Subheader } from "subheader.slint";
import { TasksGroup, TaskData, TaskState, Content } from "typedef/type.slint";
import { ButtonRegular } from "button_regular.slint";
import { TaskManager } from "task_manager.slint";
import { WebContent } from "web_content.slint";
import { Infoholder } from "infoholder.slint";
import { ButtonGrowable } from "button_growable.slint";
import { IconImage } from "icon_image.slint";
import { ModsButton } from "mods_btn.slint";
import "assets/fonts/Orbitron-Regular.ttf";
import "assets/fonts/Orbitron-Bold.ttf";
import "assets/fonts/Orbitron-ExtraBold.ttf";
import "assets/fonts/Orbitron-Medium.ttf";
import "assets/fonts/Orbitron-Black.ttf";
import "assets/fonts/Orbitron-SemiBold.ttf";
import { CleanSpinner } from "clean_spinner.slint";

export enum AppState {
	loading,
	launching,
	running,
	network_error,
	session_error,
	ready
}

component Socials {
    Infoholder {
		ButtonGrowable {
			on_click => { Callbacks.click_discord(); }

			IconImage {
				source: @image-url("assets/icons/discord.svg");
			}
		}
		ButtonGrowable {
			on_click => { Callbacks.click_youtube(); }

			IconImage {
				source: @image-url("assets/icons/youtube.svg");
			}
		}
		ButtonGrowable {
			on_click => { Callbacks.click_x(); }

			IconImage {
				source: @image-url("assets/icons/x.svg");
			}
		}
	}
}

export component Main inherits Window {
	default-font-family: "Orbitron";
	default-font-size: 17px;

	width: 1280px;
	height: 720px;
	background: #363636;
	full-screen: false;
	title: "Dystellar Launcher";

	in-out property<[TasksGroup]> groups: [];

	in-out property<AppState> app_state: loading;

	in-out property<bool> events_loading: true;
	in-out property<[Content]> events: [];
	in-out property<bool> updates_loading: true;
	in-out property<[Content]> updates: [];

	// Main window content
	VerticalLayout {
		width: 100%;
		height: 100%;
		padding: 34px;
		spacing: 20px;
		vertical-stretch: 1;
		Subheader {}
		HorizontalLayout {
			vertical-stretch: 1.0;
			spacing: 18px;
			WebContent { width: 33%; content: updates; }
			Rectangle {
				width: 33%;
				VerticalLayout {
					alignment: center;
					spacing: 12px;
					ButtonRegular {
						primary: app_state == AppState.ready;
						height: 80px;
						on_click => { Callbacks.launch() }
						HorizontalLayout {
							spacing: 8px;
							alignment: center;
							if app_state == AppState.loading : VerticalLayout { alignment: center; CleanSpinner { size: 36px; } }
							VerticalLayout {
								alignment: center;
								Text {
									font-size: 32px;
									text: app_state == AppState.ready ? "Launch" :
										app_state == AppState.session-error || app_state == AppState.network-error ? "Error" :
										app_state == AppState.launching ? "Launching" :
										app_state == AppState.running ? "Running" : "Loading...";
								}
							}
						}
					}
					HorizontalLayout {
						alignment: center;
						ModsButton {
							width: 80%;
							height: 40px;
							Text { text: "Mods"; }
							on_click => { Callbacks.show_mods() }
						}
					}

				}
			}
			WebContent { width: 33%; content: events; }
		}
		HorizontalLayout {
			alignment: space-between;
			Socials {}
			Infoholder {
				Text { text: "Dystellar Network"; }
			}
		}
	}

	TaskManager {
		groups: parent.groups;
		visible: groups.length > 0;
		opacity: 0.0;
		width: 860px;
		height: 640px;
		x: (parent.width - self.width) / 2;
		y: (parent.height - self.height) / 2 - 20px;

		states [
		    in_progress when self.visible : {
				y: (root.height - root.height) / 2;
				opacity: 1.0;

				in-out {
					animate y, opacity { duration: 230ms; easing: ease-in-out; }
				}
			}
		]
	}
}

export global Callbacks {
    callback click_discord();
    callback click_youtube();
    callback click_x();
	callback cancel_tasks();
	callback show_mods();
	callback launch();
}
