import { Subheader } from "subheader.slint";
import { DialogData, DialogType, DialogSeverity } from "typedef/dialog_utils.slint";

export global Callbacks {
    callback click_discord();
    callback click_youtube();
    callback click_x();
}

export component Main inherits Window {
	width: 1280px;
	height: 720px;
	background: #363636;

	in property<DialogData> dialog-data: { shown: false, type: DialogType.basic, severity: DialogSeverity.info, title: "", content: "" };
	callback dialog_confirmed();

	drop-shadow-blur: dialog-data.shown ? 10px : 0px;

	animate drop-shadow-blur {
		easing: ease-in-out;
		duration: 200ms;
	}

	// Dialog
	PopupWindow {
		close-on-click: false;
		opacity: 0.0;
		min-width: 400px;
		min-height: 180px;
		x: (parent.width - self.width) / 2;
		y: (parent.height - self.height) / 2 - (root.dialog-data.shown ? 0 : 20px);

		animate opacity, y {
			easing: ease-in-out;
			duration: 200ms;
		}

		Rectangle {
			padding: 12px;
			border-width: 1px;
			border-radius: 42px;
			border-color: rgba(0, 0, 0, 0.2);

			VerticalLayout {
				HorizontalLayout {
					Image {
						width: 50px;
						height: 50px;
						source: root.dialog-data.severity == DialogSeverity.info ? @image-url("assets/icons/info.svg") : @image-url("assets/icons/error.svg");
					}
				}
				HorizontalLayout {
					
				}
			}
		}
	}

	// Main window content
	VerticalLayout {
		horizontal-stretch: 1.0;
		vertical-stretch: 1.0;

		VerticalLayout {
			padding: 28px;

			Subheader {}
		}
	}
}
