import { Subheader } from "subheader.slint";
import { DialogData, DialogType, DialogSeverity } from "typedef/dialog_utils.slint";
import { TasksGroup, TaskData, TaskState, TaskType, Content } from "typedef/type.slint";
import { ButtonRegular } from "button_regular.slint";
import { TaskManager } from "task_manager.slint";
import { WebContent } from "web_content.slint";
import { Infoholder } from "infoholder.slint";
import { ButtonGrowable } from "button_growable.slint";
import { IconImage } from "icon_image.slint";
import "assets/fonts/Orbitron-Regular.ttf";
import "assets/fonts/Orbitron-Bold.ttf";
import "assets/fonts/Orbitron-ExtraBold.ttf";
import "assets/fonts/Orbitron-Medium.ttf";
import "assets/fonts/Orbitron-Black.ttf";
import "assets/fonts/Orbitron-SemiBold.ttf";

export enum AppState {
	loading,
	network_error,
	session_error,
	ready
}

component Socials {
    Infoholder {
		ButtonGrowable {
			on_click => { Callbacks.click_discord(); }

			IconImage {
				source: @image-url("assets/icons/discord.svg");
			}
		}
		ButtonGrowable {
			on_click => { Callbacks.click_youtube(); }

			IconImage {
				source: @image-url("assets/icons/youtube.svg");
			}
		}
		ButtonGrowable {
			on_click => { Callbacks.click_x(); }

			IconImage {
				source: @image-url("assets/icons/x.svg");
			}
		}
	}
}

export component Main inherits Window {
	public function hide_popup() {
		dialog-data.shown = false;
	    popup.close();
	}

	public function show_popup() {
	    popup.show();
	}

	default-font-family: "Orbitron";
	default-font-size: 17px;

	width: 1280px;
	height: 720px;
	background: #363636;
	full-screen: false;
	title: "Dystellar Launcher";

	in-out property <[TasksGroup]> groups: [];
	in-out property <float> total_task_progress: 0.0;
	callback cancel_tasks();

	in-out property<DialogData> dialog-data: { shown: false, type: DialogType.basic, severity: DialogSeverity.info, content: "" };
	in-out property<AppState> app_state: loading;
	callback dialog_confirmed();

	in-out property <[Content]> events: [];
	in-out property <[Content]> updates: [];

	TaskManager {
		groups: parent.groups;
		visible: groups.length > 0;
		opacity: groups.length > 0 ? 1.0 : 0.0;
		width: 860px;
		height: 640px;
		x: (parent.width - self.width) / 2;
		y: (parent.height - self.height) / 2 - (groups.length > 0 ? 0 : 20px);

		animate opacity, y {
			easing: ease-in-out;
			duration: 200ms;
		}
	}

	// Dialog
	popup := PopupWindow {
		close-policy: no-auto-close;
		visible: root.dialog-data.shown;
		opacity: root.dialog-data.shown ? 1.0 : 0.0;
		width: 400px;
		min-height: 180px;
		x: (parent.width - self.width) / 2;
		y: (parent.height - self.height) / 2 - (root.dialog-data.shown ? 0 : 20px);

		animate opacity, y {
			easing: ease-in-out;
			duration: 200ms;
		}
		Rectangle {
			border-width: 1px;
			border-radius: 42px;
			border-color: rgba(0, 0, 0, 0.2);
			drop-shadow-blur: 8px;
			VerticalLayout {
				spacing: 20px;
				alignment: space-around;
				HorizontalLayout {
					alignment: start;
					Image {
						width: 50px;
						height: 50px;
						source: root.dialog-data.severity == DialogSeverity.info ? @image-url("assets/icons/info.svg") : @image-url("assets/icons/error.svg");
					}
					Text { text: dialog-data.content; }
				}
				HorizontalLayout {
					alignment: end;
					ButtonRegular {
						visible: dialog-data.type == DialogType.confirmation;
						primary: false;
						on_click => { hide_popup() }
						Text { text: "Cancel"; }
					}
					ButtonRegular {
						primary: true;
						on_click => {
							hide_popup();

							if (dialog-data.type == DialogType.confirmation) {
								dialog_confirmed();
							}
						}
						Text { text: dialog-data.type == DialogType.confirmation ? "Proceed" : "Ok"; }
					}
				}
			}
		}
	}

	// Main window content
	VerticalLayout {
		width: 100%;
		height: 100%;
		padding: 34px;
		spacing: 20px;
		vertical-stretch: 1;
		Subheader {}
		HorizontalLayout {
			vertical-stretch: 1.0;
			spacing: 18px;
			WebContent { content: updates; }
			Rectangle {
				ButtonRegular {
					primary: true;
					height: 80px;
					Text { text: "Loading..."; font-size: 32px; }
				}
			}
			WebContent { content: events; }
		}
		HorizontalLayout {
			alignment: space-between;
			Socials {}
			Infoholder {
				Text { text: "Dystellar Network"; }
			}
		}
	}
}

export global Callbacks {
    callback click_discord();
    callback click_youtube();
    callback click_x();
}
