import { Container } from "container.slint";
import { CleanSpinner } from "clean_spinner.slint";
import { ButtonRegular } from "button_regular.slint";
import { ToggleSlider } from "toggle_slider.slint";
import { Mod } from "typedef/type.slint";
import "assets/fonts/Orbitron-Regular.ttf";
import "assets/fonts/Orbitron-Bold.ttf";
import "assets/fonts/Orbitron-ExtraBold.ttf";
import "assets/fonts/Orbitron-Medium.ttf";
import "assets/fonts/Orbitron-Black.ttf";
import "assets/fonts/Orbitron-SemiBold.ttf";

component ModCard inherits Container {
	callback on_click();
	callback on_toggle();
    in-out property <Mod> mod;

	background: area.pressed ? rgba(0, 0, 0, 0.1) : area.has-hover ? rgba(255, 255, 255, 0.19) : rgba(255, 255, 255, 0.09);
	width: 100%;
	height: 128px;
	area := TouchArea {
		clicked => { on_click() }
	}

	HorizontalLayout {
		alignment: space-between;
		VerticalLayout { alignment: center; Rectangle {
			height: 100%;
			width: self.height;
			clip: true;
			border-radius: 12px;
			drop-shadow-color: black;
			drop-shadow-offset-y: 2px;
			drop-shadow-blur: 4px;
			if root.mod.loading : CleanSpinner {
				size: parent.width * 0.6;
				x: (parent.width - self.size) / 2;
				y: (parent.height - self.size) / 2;
			}
			Image {
				source: root.mod.image;
				width: 100%;
				height: 100%;
				image-fit: cover;
			}
		}}
		VerticalLayout { alignment: center; HorizontalLayout {
			alignment: center;
			spacing: 4px;
			Text { text: mod.name; font-size: 24px; }
			Text {
				text: mod.version;
				color: rgba(255, 255, 255, 0.3);
				font-size: 14px;
			}
		}}
		VerticalLayout { alignment: center; ToggleSlider { toggle => { on_toggle() } } }
	}
}

export component ModsUI inherits Window {
    default-font-family: "Orbitron";
	default-font-size: 17px;

	callback close();
	callback mod_click(mod: Mod);
	callback mod_toggle(mod: Mod);

	in-out property <[Mod]> mods;
	in-out property <bool> loading: true;

	width: 660px;
	height: 640px;
	background: #363636;
	full-screen: false;
	title: "Optional Mods Selection";

	CleanSpinner {
		spinning: loading;
		size: 128px;
		opacity: loading ? 1 : 0;
		x: (root.width - self.size) / 2;
		y: (root.height - self.size) / 2;

		animate opacity { duration: 230ms; easing: ease-in-out; }
	}

	VerticalLayout {
		padding: 6px;
		spacing: 6px;
		Flickable {
			height: 80%;
			viewport-height: self.height;
			for mod in root.mods : ModCard { mod: mod; }
		}
		HorizontalLayout {
			height: 20%;
			alignment: end;
			padding-right: 26px;
			ButtonRegular {
				height: 40px;
				width: 400px;
				primary: true;
				Text { text: "Done"; }
				on_click => { root.close() }
			}
		}
	}
}
