import { Infoholder } from "infoholder.slint";
import { ButtonGrowable } from "button_growable.slint";
import { IconImage } from "icon_image.slint";
import { Callbacks } from "main.slint";

export component Socials {
    Infoholder {
		ButtonGrowable {
			on_click => { Callbacks.click_discord(); }

			IconImage {
				source: @image-url("assets/icons/discord.svg");
			}
		}
		ButtonGrowable {
			on_click => { Callbacks.click_youtube(); }

			IconImage {
				source: @image-url("assets/icons/youtube.svg");
			}
		}
		ButtonGrowable {
			on_click => { Callbacks.click_x(); }

			IconImage {
				source: @image-url("assets/icons/x.svg");
			}
		}
	}
}
