import { Infoholder } from "infoholder.slint";
import { ButtonGrowable } from "button_growable.slint";
import { IconImage } from "icon_image.slint";

export component Subheader inherits HorizontalLayout {
	Infoholder {
		ButtonGrowable {
			IconImage {
				source: @image-url("assets/icons/settings.svg");
			}
		}
		ButtonGrowable {
			width: store.width;
			store := Text {
				text: "Store";
			}
		}
	}

	Rectangle {
		horizontal-stretch: 1.0;
	}

	Infoholder {

	}
}
