import { Infoholder } from "infoholder.slint";
import { ButtonGrowable } from "button_growable.slint";
import { IconImage } from "icon_image.slint";

export component Subheader inherits HorizontalLayout {
	alignment: space-between;
	Infoholder {
		ButtonGrowable {
			IconImage { source: @image-url("assets/icons/settings.svg"); }
		}
		ButtonGrowable {
			Text { text: "Store"; }
		}
		ButtonGrowable {
			Text { text: "ToS"; }
		}
	}
	Infoholder {
		ButtonGrowable {
			IconImage { source: @image-url("assets/icons/info.svg"); }
		}
	}
}
