import { HoverableText } from "hoverable_text.slint";
import { TasksGroup, TaskData, TaskState } from "typedef/type.slint";
import { ProgressBar } from "progress_bar.slint";
import { ButtonRegular } from "button_regular.slint";
import { ListView, VerticalBox } from "std-widgets.slint";

component Tooltip inherits Rectangle {
	in-out property <string> text: "";

	background: rgba(0, 0, 0, 0.8);
	border-color: white;
	border-radius: 12px;
	border-width: 1px;
	animate opacity {
		duration: 180ms;
		easing: ease-in-out;
	}

	HorizontalLayout {
		padding-top: 1px;
		padding-bottom: 1px;
		padding-left: 3px;
		padding-right: 3px;
		alignment: center;
		Text {
			text: root.text;
		}
	}
}

component TaskItem inherits HorizontalLayout {
	in-out property <TaskData> task;

	padding-left: 6px;
	alignment: space-between;
	area := TouchArea {}
	Text {
		text: task.name;
		width: 360px;
		overflow: elide;
		horizontal-alignment: left;
	}
	/*Tooltip {
		opacity: area.has-hover ? 1.0 : 0.0;
		text: task.details;
	}*/
	ProgressBar {
		width: 150px;
		height: 35px;
		color: task.state == TaskState.finished ? #056800 : task.state == TaskState.failed ? #680000 : #006856;
		progress: task.progress;
		content: task.state == TaskState.in-progress ? "In Progress" :
					task.state == TaskState.verifying ? "Verifying" :
					task.state == TaskState.unpacking ? "Unpacking" :
					task.state == TaskState.starting ? "Starting" :
					task.state == TaskState.waiting ? "Waiting" :
					task.state == TaskState.finished ? "Finished" : "Failed";
	}
}

component Group inherits VerticalLayout {
	in-out property <TasksGroup> group;

	width: 100%;
	padding-left: 12px;
	spacing: 6px;
	Text {
		text: group.name;
	}
	for i in min(16, group.tasks.length): TaskItem {
		width: 100%;
		task: group.tasks[i];
	}
}

export component TaskManager inherits Rectangle {
	in-out property <[TasksGroup]> groups: [];
	in-out property <float> total_progress: 0.0;
	background: #252525;
	border-radius: 24px;

	VerticalLayout {
		vertical-stretch: 1;
		horizontal-stretch: 1;
		padding: 10px;
		alignment: center;
		spacing: 6px;
		HorizontalLayout {
			spacing: 6px;
			Text { text: "Tasks"; color: white; }
			Rectangle { horizontal-stretch: 1; height: 1px; border-width: 1px; border-color: white; border-radius: 2px; }
			ProgressBar { progress: total_progress; }
		}
		ListView {
			width: 100%;
			height: 80%;
			
			for i in min(4, groups.length): Group {
				group: groups[i];
			}
		}
	}
}
