export component ToggleSlider inherits Rectangle {
	callback toggle();
    in-out property <bool> enabled: false;

	width: 60px;
	height: 30px;
	background: enabled ? #006857 : rgba(0, 0, 0, 0.2);
	border-radius: 500px;
	animate background { duration: 250ms; easing: ease-in-out; }

	TouchArea {
		clicked => { toggle() }
	}

	Rectangle {
		width: root.height;
		height: root.height;
		x: enabled ? (parent.width - self.width) : 0px;
		y: 0px;
		background: white;
		border-color: #E4E4E4;
		border-width: 1px;
		border-radius: 500px;
		animate x { duration: 250ms; easing: ease-in-out; }
	}
}
