import { ButtonRegular } from "button_regular.slint";
import { CleanSpinner } from "clean_spinner.slint";

export component WelcomeUI inherits Window {
	background: #363636;
	title: "Dystellar Launcher | Welcome";
	default-font-size: 20px;
	full-screen: false;
	width: 480px;
	height: 540px;

	in-out property <bool> waiting: false;

	callback login();

	VerticalLayout {
		padding: 46px;
		alignment: space-between;
		Text {
			horizontal-alignment: center;
			text: "Welcome!";
			font-size: 64px;
			font-weight: 650;
			color: white;
		}
		HorizontalLayout {
			alignment: center;
			VerticalLayout {
				alignment: center;
				spacing: 0px;
				padding: 14px;
				padding-left: 18px;
				padding-right: 18px;
				HorizontalLayout {
					alignment: center;
					Rectangle {
						background: #282828;
						border-radius: 32px;
						border-width: 1px;
						border-color: #353535;
						width: label.preferred-width + 64px;
						height: label.preferred-height + 12px;
						label := Text { text: "Sign in with Microsoft:"; color: white; }
					}
				}
				HorizontalLayout {
					ButtonRegular {
						primary: true;
						width: 320px;
						height: 80px;
						on_click => {
							waiting = true;
							login();
						}
						HorizontalLayout {
							alignment: center;
							spacing: 12px;
							padding: 16px;
							if (waiting): VerticalLayout {
								alignment: center;
								CleanSpinner { size: 32px; }
							}
							Image {
								source: @image-url("assets/icons/microsoft.png");
								height: 100%;
								width: self.height;
								image-fit: contain;
							}
							Text {
								font-size: 38px;
								text: "Microsoft";
								vertical-alignment: center;
							}
						}
					}
				}
			}
		}
		HorizontalLayout {
			alignment: center;
			Image {
				source: @image-url("assets/icons/dystlogo.png");
				width: 96px;
				height: 96px;
			}
		}
	}
}
